name: create vcard QR-Code and publish pages

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create VCards
        run: |
          for f in ./*.txt; do
            cat $f | base64 -d >> $f.vcf
          done
      
      - name: Cut Photos out
        run: |
          for f in ./*.vcf; do
            echo "$(sed -n '/PHOTO/q;p' $f)" > $f
            echo "END:VCARD" >> $f
          done
          
      - name: Generate QR-Codes
        run: |
          sudo apt-get install qrencode -y
          for f in ./*.vcf; do
            vcard=$(<$f)
            qrencode -o $f.png "$vcard" 
          done
      
      - name: create artifact folder
        run: |
          mkdir output
          cp *.png output/
          cp *.js output/
          cp *.html output/
          cp *.txt output/
            
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
            
